### PR TITLE
Fix query size issue with use_post_method enabled

### PR DESCRIPTION
**Pull request by bubasuma**
When Searching with use_post_method enabled it puts parameters on both the URL and in request body. This can cause duplicate parameters on some RETS servers.

Also can cause the URL to be too long in some cases where there are lots of fields in Select which is one of the main reasons to use POST instead of GET to get over this limitation.

#205

### CODE REVIEW

**Comment by bubasuma** [comment]
@bwolven what makes u think that the URL at this point contains the query parameters?
I am working with this package for long time, and I am pretty sure the URL is cleaned from query parameters. it would contain both query parameters and post data if `$options['query']` was not unset. 

I suggest you to debug the request.

**Comment by bwolven** [comment]
Sorry about that. My mistake. I should have looked at the code more carefully and seen that it was setting it in last_request_url not the actual URL. That being said though, wouldn't your removing it from the $options break the recursive retry logic since it passes the $options with query removed into the retry request?

**Comment by bubasuma** [comment]
@bwolven good point about the retry.

**Comment by troydavisson** [comment]
I just merged #241 which should address the issues with incorrectly including query parameters when using POST.

**Pull request closed without merging**
